- name: install epel
  yum:
    name: epel-release
    state: present
  tags: [nginx]
                        
- name: install nginx
  yum:
    name: nginx
    state: present
  tags: [nginx]

- name: enable nginx
  service:
    name: nginx
    state: started
  tags: [nginx, status]
